//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The_Web_Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobsTable
    {
        public int Id { get; set; }
        public string JobName { get; set; }
        public string clientId { get; set; }
        public string JobStatus { get; set; }
    }
}
